name: daily_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  table_calendar: ^3.0.0
  flutter_localization: ^0.2.2
  shared_preferences: ^2.1.0
  intl: ^0.19.0
  sqflite: ^2.2.6
  path: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

